import exercicio_01 from "./exercicios/exercicio-01.js";
import exercicio_02 from "./exercicios/exercicio-02.js";
import exercicio_03 from "./exercicios/exercicio-03.js";
import exercicio_04 from "./exercicios/exercicio-04.js";
import exercicio_05 from "./exercicios/exercicio-05.js";
import exercicio_06 from "./exercicios/exercicio-06.js";
import exercicio_07 from "./exercicios/exercicio-07.js";
import exercicio_08 from "./exercicios/exercicio-08.js";
exercicio_01();
exercicio_02();
exercicio_03();
exercicio_04();
exercicio_05();
exercicio_06();
exercicio_07();
exercicio_08();
